#!/usr/bin/env bash 

# Copy file and detelt the file cotent

path=/Users/yu.an/Desktop/Bash
file=helloworld
if [ ! -f "$path/$file" ]
then
  	echo "no file"
else
	cp $path/helloworld $path/helloworld.old
        cat /dev/null>$path/helloworld
        echo done
fi
exit 0  
